
import java.awt.Color;
import panels.RoundPanel;
import javax.swing.table.*;
import java.util.*;
import javax.swing.JButton;
import scrollbar.ScrollBarCustom;
import table.TableCustom;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class POS extends javax.swing.JFrame {
    
    private HashMap<String, Double> products = new HashMap<String, Double>();
    private HashMap<String, String> prodNames = new HashMap<String, String>();

    private String horizontalLine = " ============================================";


    /**
     * Creates new form POS
     */
    public POS() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        TableCustom.apply(jScrollPane3, TableCustom.TableType.DEFAULT);
        double[] prices = {15.00, 20.00, 17.50, 45.50};
        String[] ids = {"P1", "P2", "P3", "P4"};
        String[] names = {"Product1", "Product2", "Product3", "Product4"};
        for (int i = 0; i < ids.length; i++) {
            products.put(ids[i], prices[i]);
            prodNames.put(names[i], ids[i]);
        }
        disableButtons();
//        testData(mainTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        roundPanel1 = new panels.RoundPanel();
        btn1 = new button.Button();
        btn2 = new button.Button();
        btn3 = new button.Button();
        btn4 = new button.Button();
        jScrollPane3 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        roundPanel4 = new panels.RoundPanel();
        jLabel4 = new javax.swing.JLabel();
        finalTotal = new javax.swing.JLabel();
        roundPanel5 = new panels.RoundPanel();
        jLabel7 = new javax.swing.JLabel();
        resetBtn = new button.Button();
        addBtn2 = new button.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        receipt = new javax.swing.JTextArea();
        roundPanel6 = new panels.RoundPanel();
        hundredQtyBtn = new button.Button();
        totalField = new textfield.TextField();
        addBtn = new button.Button();
        jLabel1 = new javax.swing.JLabel();
        productField = new textfield.TextField();
        clearQty = new button.Button();
        priceField = new textfield.TextField();
        qtyField = new textfield.TextField();
        oneQtyBtn = new button.Button();
        fiveQtyBtn = new button.Button();
        twentyQtyBtn = new button.Button();
        fiftyQtyBtn = new button.Button();
        twoQtyBtn = new button.Button();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        payNotif = new javax.swing.JLabel();
        Pay = new button.Button();
        payField = new textfield.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel9.setFont(new java.awt.Font("Oswald", 0, 36)); // NOI18N
        jLabel9.setText("Insert name here...");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        roundPanel1.setBackground(new java.awt.Color(244, 248, 222));
        roundPanel1.setBorderRadius(15);

        btn1.setBackground(new java.awt.Color(244, 248, 222));
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/01.png"))); // NOI18N
        btn1.setText("P1-Product1");
        btn1.setRippleColor(new java.awt.Color(0, 153, 153));
        btn1.setRound(15);
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(244, 248, 222));
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/02.png"))); // NOI18N
        btn2.setText("P2-Product2");
        btn2.setRippleColor(new java.awt.Color(0, 153, 153));
        btn2.setRound(15);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(244, 248, 222));
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/03.png"))); // NOI18N
        btn3.setText("P3-Product3");
        btn3.setToolTipText("");
        btn3.setRippleColor(new java.awt.Color(0, 153, 153));
        btn3.setRound(15);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(244, 248, 222));
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/04.png"))); // NOI18N
        btn4.setText("P4-Product4");
        btn4.setToolTipText("");
        btn4.setRippleColor(new java.awt.Color(0, 153, 153));
        btn4.setRound(15);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(255, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(roundPanel1);

        jScrollPane2.setVerticalScrollBar(new ScrollBarCustom());

        mainTable.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(mainTable);
        if (mainTable.getColumnModel().getColumnCount() > 0) {
            mainTable.getColumnModel().getColumn(0).setResizable(false);
            mainTable.getColumnModel().getColumn(1).setResizable(false);
            mainTable.getColumnModel().getColumn(2).setResizable(false);
            mainTable.getColumnModel().getColumn(2).setPreferredWidth(20);
            mainTable.getColumnModel().getColumn(3).setResizable(false);
        }

        roundPanel4.setBackground(new java.awt.Color(244, 248, 222));
        roundPanel4.setBorderRadius(15);

        jLabel4.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Total:");

        finalTotal.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        finalTotal.setForeground(new java.awt.Color(153, 153, 153));
        finalTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        finalTotal.setText("0.00");

        javax.swing.GroupLayout roundPanel4Layout = new javax.swing.GroupLayout(roundPanel4);
        roundPanel4.setLayout(roundPanel4Layout);
        roundPanel4Layout.setHorizontalGroup(
            roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(finalTotal)
                .addGap(8, 8, 8))
        );
        roundPanel4Layout.setVerticalGroup(
            roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finalTotal)
                    .addComponent(jLabel4))
                .addGap(15, 15, 15))
        );

        roundPanel5.setBackground(new java.awt.Color(244, 248, 222));
        roundPanel5.setBorderRadius(15);

        jLabel7.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Receipt:");

        resetBtn.setBackground(new java.awt.Color(146, 255, 253));
        resetBtn.setText("Reset");
        resetBtn.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        resetBtn.setRippleColor(new java.awt.Color(0, 153, 153));
        resetBtn.setRound(15);
        resetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resetBtnMousePressed(evt);
            }
        });

        addBtn2.setBackground(new java.awt.Color(146, 255, 253));
        addBtn2.setText("Print");
        addBtn2.setEnabled(false);
        addBtn2.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        addBtn2.setRippleColor(new java.awt.Color(0, 153, 153));
        addBtn2.setRound(15);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        receipt.setEditable(false);
        receipt.setBackground(new java.awt.Color(255, 255, 255));
        receipt.setColumns(20);
        receipt.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        receipt.setForeground(new java.awt.Color(0, 0, 0));
        receipt.setRows(5);
        receipt.setTabSize(4);
        receipt.setText(" ============================================");
        receipt.setDragEnabled(true);
        jScrollPane1.setViewportView(receipt);

        jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());

        javax.swing.GroupLayout roundPanel5Layout = new javax.swing.GroupLayout(roundPanel5);
        roundPanel5.setLayout(roundPanel5Layout);
        roundPanel5Layout.setHorizontalGroup(
            roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
                .addContainerGap())
        );
        roundPanel5Layout.setVerticalGroup(
            roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(roundPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        roundPanel6.setBackground(new java.awt.Color(244, 248, 222));
        roundPanel6.setBorderRadius(15);

        hundredQtyBtn.setBackground(new java.awt.Color(146, 255, 253));
        hundredQtyBtn.setText("100");
        hundredQtyBtn.setEnabled(false);
        hundredQtyBtn.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        hundredQtyBtn.setRippleColor(new java.awt.Color(0, 153, 153));
        hundredQtyBtn.setRound(15);
        hundredQtyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hundredQtyBtnActionPerformed(evt);
            }
        });

        totalField.setEditable(false);
        totalField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalField.setText("0");
        totalField.setToolTipText("Price");
        totalField.setFont(new java.awt.Font("HelveticaNeueLT Std", 1, 24)); // NOI18N
        totalField.setRound(15);
        totalField.setShadowColor(new java.awt.Color(102, 102, 102));

        addBtn.setBackground(new java.awt.Color(146, 255, 253));
        addBtn.setText("Add");
        addBtn.setEnabled(false);
        addBtn.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        addBtn.setRippleColor(new java.awt.Color(0, 153, 153));
        addBtn.setRound(15);
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Price");

        productField.setEditable(false);
        productField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        productField.setToolTipText("Price");
        productField.setFont(new java.awt.Font("HelveticaNeueLT Std", 1, 24)); // NOI18N
        productField.setRound(15);
        productField.setShadowColor(new java.awt.Color(102, 102, 102));

        clearQty.setBackground(new java.awt.Color(146, 255, 253));
        clearQty.setText("<");
        clearQty.setEnabled(false);
        clearQty.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        clearQty.setRippleColor(new java.awt.Color(0, 153, 153));
        clearQty.setRound(15);
        clearQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearQtyActionPerformed(evt);
            }
        });

        priceField.setEditable(false);
        priceField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        priceField.setText("0.00");
        priceField.setToolTipText("Price");
        priceField.setFont(new java.awt.Font("HelveticaNeueLT Std", 1, 24)); // NOI18N
        priceField.setRound(15);
        priceField.setShadowColor(new java.awt.Color(102, 102, 102));

        qtyField.setEditable(false);
        qtyField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        qtyField.setText("0");
        qtyField.setToolTipText("Quantity");
        qtyField.setFont(new java.awt.Font("HelveticaNeueLT Std", 1, 24)); // NOI18N
        qtyField.setRound(15);
        qtyField.setShadowColor(new java.awt.Color(102, 102, 102));

        oneQtyBtn.setBackground(new java.awt.Color(146, 255, 253));
        oneQtyBtn.setText("1");
        oneQtyBtn.setEnabled(false);
        oneQtyBtn.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        oneQtyBtn.setRippleColor(new java.awt.Color(0, 153, 153));
        oneQtyBtn.setRound(15);
        oneQtyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneQtyBtnActionPerformed(evt);
            }
        });

        fiveQtyBtn.setBackground(new java.awt.Color(146, 255, 253));
        fiveQtyBtn.setText("5");
        fiveQtyBtn.setEnabled(false);
        fiveQtyBtn.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        fiveQtyBtn.setRippleColor(new java.awt.Color(0, 153, 153));
        fiveQtyBtn.setRound(15);
        fiveQtyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveQtyBtnActionPerformed(evt);
            }
        });

        twentyQtyBtn.setBackground(new java.awt.Color(146, 255, 253));
        twentyQtyBtn.setText("20");
        twentyQtyBtn.setEnabled(false);
        twentyQtyBtn.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        twentyQtyBtn.setRippleColor(new java.awt.Color(0, 153, 153));
        twentyQtyBtn.setRound(15);
        twentyQtyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentyQtyBtnActionPerformed(evt);
            }
        });

        fiftyQtyBtn.setBackground(new java.awt.Color(146, 255, 253));
        fiftyQtyBtn.setText("50");
        fiftyQtyBtn.setEnabled(false);
        fiftyQtyBtn.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        fiftyQtyBtn.setRippleColor(new java.awt.Color(0, 153, 153));
        fiftyQtyBtn.setRound(15);
        fiftyQtyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiftyQtyBtnActionPerformed(evt);
            }
        });

        twoQtyBtn.setBackground(new java.awt.Color(146, 255, 253));
        twoQtyBtn.setText("2");
        twoQtyBtn.setEnabled(false);
        twoQtyBtn.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        twoQtyBtn.setRippleColor(new java.awt.Color(0, 153, 153));
        twoQtyBtn.setRound(15);
        twoQtyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoQtyBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Total");

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Qty");

        payNotif.setBackground(java.awt.Color.gray);
        payNotif.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        payNotif.setForeground(new java.awt.Color(153, 153, 153));
        payNotif.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        payNotif.setText("Cash");

        Pay.setBackground(new java.awt.Color(146, 255, 253));
        Pay.setText("Pay");
        Pay.setEnabled(false);
        Pay.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        Pay.setRippleColor(new java.awt.Color(0, 153, 153));
        Pay.setRound(15);
        Pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayActionPerformed(evt);
            }
        });

        payField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        payField.setText("0");
        payField.setToolTipText("Price");
        payField.setFont(new java.awt.Font("HelveticaNeueLT Std", 1, 24)); // NOI18N
        payField.setRound(15);
        payField.setShadowColor(new java.awt.Color(102, 102, 102));
        payField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                payFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout roundPanel6Layout = new javax.swing.GroupLayout(roundPanel6);
        roundPanel6.setLayout(roundPanel6Layout);
        roundPanel6Layout.setHorizontalGroup(
            roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel6Layout.createSequentialGroup()
                .addGroup(roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel6Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(payNotif)
                        .addGap(14, 14, 14))
                    .addGroup(roundPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Pay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(roundPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, roundPanel6Layout.createSequentialGroup()
                                    .addGroup(roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(roundPanel6Layout.createSequentialGroup()
                                            .addComponent(fiftyQtyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(hundredQtyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(clearQty, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(roundPanel6Layout.createSequentialGroup()
                                            .addGroup(roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel2))
                                            .addGap(17, 17, 17)
                                            .addGroup(roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(qtyField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(payField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(roundPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oneQtyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twoQtyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fiveQtyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twentyQtyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundPanel6Layout.setVerticalGroup(
            roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel6Layout.createSequentialGroup()
                .addComponent(productField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(priceField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneQtyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twoQtyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiveQtyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twentyQtyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fiftyQtyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hundredQtyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(payNotif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addComponent(roundPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(roundPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(roundPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roundPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(roundPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(roundPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayActionPerformed
        Double cash = Double.parseDouble(payField.getText());
    }//GEN-LAST:event_PayActionPerformed

    private void payFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_payFieldKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c))
        evt.consume();
    }//GEN-LAST:event_payFieldKeyTyped

    private void clearQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearQtyActionPerformed
        String id = "0";
        addQty(id);
    }//GEN-LAST:event_clearQtyActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBtnActionPerformed

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        String name = productField.getText();
        if (!name.isEmpty()) {
            String id = prodNames.get(name);
            String price = priceField.getText();
            String qty = qtyField.getText();
            String total = totalField.getText();
            Object[] data = new Object[]{id+"-"+name, price, qty, total};
            addData(data);
            clear();
        }
    }//GEN-LAST:event_addBtnMouseClicked

    private void hundredQtyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hundredQtyBtnActionPerformed
        JButton source = (JButton) evt.getSource();
        String id = source.getText();
        addQty(id);
    }//GEN-LAST:event_hundredQtyBtnActionPerformed

    private void twoQtyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoQtyBtnActionPerformed
        JButton source = (JButton) evt.getSource();
        String id = source.getText();
        addQty(id);
    }//GEN-LAST:event_twoQtyBtnActionPerformed

    private void fiftyQtyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiftyQtyBtnActionPerformed
        JButton source = (JButton) evt.getSource();
        String id = source.getText();
        addQty(id);
    }//GEN-LAST:event_fiftyQtyBtnActionPerformed

    private void twentyQtyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentyQtyBtnActionPerformed
        JButton source = (JButton) evt.getSource();
        String id = source.getText();
        addQty(id);
    }//GEN-LAST:event_twentyQtyBtnActionPerformed

    private void fiveQtyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveQtyBtnActionPerformed
        JButton source = (JButton) evt.getSource();
        String id = source.getText();
        addQty(id);
    }//GEN-LAST:event_fiveQtyBtnActionPerformed

    private void oneQtyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneQtyBtnActionPerformed
        JButton source = (JButton) evt.getSource();
        String id = source.getText();
        addQty(id);
    }//GEN-LAST:event_oneQtyBtnActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        JButton source = (JButton) evt.getSource();
        String id = source.getText();
        pickProduct(id);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        JButton source = (JButton) evt.getSource();
        String id = source.getText();
        pickProduct(id);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        JButton source = (JButton) evt.getSource();
        String id = source.getText();
        pickProduct(id);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        JButton source = (JButton) evt.getSource();
        String id = source.getText();
        pickProduct(id);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1MouseClicked

    private void resetBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetBtnMousePressed
        resetAll();
    }//GEN-LAST:event_resetBtnMousePressed

    private void notifyPayment() {
        payNotif.setText("Not enough cash.");
        payNotif.setForeground(Color.red);
    }

    private void addQty (String num) {
        int amount = Integer.parseInt(num);
        int current = Integer.parseInt(qtyField.getText()) + amount;
        if (amount == 0) {
            current = 0;
        }
        qtyField.setText("" + current);
        Double price = Double.valueOf(priceField.getText());
        Double total = price * current;
        totalField.setText(total.toString());
    } 
    private void pickProduct(String id) {
        String[] prod = id.split("-");
        String name = prod[1];
        String key = prod[0];
        Double price = products.get(key);
        productField.setText(name);
        priceField.setText(String.format("%.2f", price));
        qtyField.setText("1");
        totalField.setText(String.format("%.2f", price));
        checkButtons();
    }
    
    private void addData(Object [] data) {
        DefaultTableModel model = (DefaultTableModel) mainTable.getModel();
        Boolean flag = true;
        int index = -1;
        for (int i = 0; i < model.getRowCount(); i++) {
            String name =  model.getValueAt(i, 0).toString();
            if (data[0].equals(name)) {
                flag = false;
                index = i;
                break;
            }
        }
        if (flag) {
            model.addRow(data);
            updateTotal();
        } else {
            Double current = Double.valueOf(model.getValueAt(index, 3).toString());
            int qty = Integer.parseInt(model.getValueAt(index, 2).toString());
            Double total = Double.valueOf(data[3].toString()) + current;
            int totalQty = Integer.parseInt(data[2].toString()) + qty;
            model.setValueAt(String.valueOf(totalQty), index, 2);
            model.setValueAt(String.format("%.2f", total), index, 3);
            updateTotal();
        }
    }
    
    private void clear() {
        productField.setText("");
        priceField.setText("0.00");
        qtyField.setText("0");
        totalField.setText("0.00");
        
        checkButtons();
    }
    
    private void updateTotal() {
        DefaultTableModel model = (DefaultTableModel) mainTable.getModel();
        Double total = 0.00;
        for (int i = 0; i < model.getRowCount(); i++) {
            total += Double.valueOf(model.getValueAt(i, 3).toString());
        }
        finalTotal.setText(String.format("%.2f", total));
    }
    
    private void clearTable() {
        ((DefaultTableModel)mainTable.getModel()).setRowCount(0);
    }
    
    private void resetAll() {
        receipt.setText(horizontalLine);
        finalTotal.setText("0.00");
        clear();
        clearTable();
        checkButtons();
    }
    
    private void disableButtons() {
        oneQtyBtn.setEnabled(false);
        clearQty.setEnabled(false);
        hundredQtyBtn.setEnabled(false);
        fiftyQtyBtn.setEnabled(false);
        twentyQtyBtn.setEnabled(false);
        fiveQtyBtn.setEnabled(false);
        twoQtyBtn.setEnabled(false);
        addBtn.setEnabled(false);
    }
    
    private void checkButtons() {
        if (productField.getText().isEmpty()) {
            oneQtyBtn.setEnabled(false);
            clearQty.setEnabled(false);
            hundredQtyBtn.setEnabled(false);
            fiftyQtyBtn.setEnabled(false);
            twentyQtyBtn.setEnabled(false);
            fiveQtyBtn.setEnabled(false);
            twoQtyBtn.setEnabled(false);
        } else {
            oneQtyBtn.setEnabled(true);
            clearQty.setEnabled(true);
            hundredQtyBtn.setEnabled(true);
            fiftyQtyBtn.setEnabled(true);
            twentyQtyBtn.setEnabled(true);
            fiveQtyBtn.setEnabled(true);
            twoQtyBtn.setEnabled(true);
        }
        
        if (Double.parseDouble(totalField.getText()) == 0.00) {
            addBtn.setEnabled(false);
        } else {
            addBtn.setEnabled(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.Button Pay;
    private button.Button addBtn;
    private button.Button addBtn2;
    private button.Button btn1;
    private button.Button btn2;
    private button.Button btn3;
    private button.Button btn4;
    private button.Button clearQty;
    private button.Button fiftyQtyBtn;
    private javax.swing.JLabel finalTotal;
    private button.Button fiveQtyBtn;
    private button.Button hundredQtyBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable mainTable;
    private button.Button oneQtyBtn;
    private textfield.TextField payField;
    private javax.swing.JLabel payNotif;
    private textfield.TextField priceField;
    private textfield.TextField productField;
    private textfield.TextField qtyField;
    private javax.swing.JTextArea receipt;
    private button.Button resetBtn;
    private panels.RoundPanel roundPanel1;
    private panels.RoundPanel roundPanel4;
    private panels.RoundPanel roundPanel5;
    private panels.RoundPanel roundPanel6;
    private textfield.TextField totalField;
    private button.Button twentyQtyBtn;
    private button.Button twoQtyBtn;
    // End of variables declaration//GEN-END:variables
}